Sprint1/step2
Jik789/react-burger pull request #2
Opened 2023-05-31 07:22 UTC by Jik789

2023-05-31 20:47 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Реализовали закрытие модалки по ESC
- Протипизировали все компоненты

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Верстка поехала у названий категорий

<img width="572" alt="Снимок экрана 2023-05-31 в 23 43 21" src="https://github.com/Jik789/react-burger/assets/60173362/1656fb70-fe1e-49fe-a714-55b7cbb8636b">

- Добавьте проверку ответа сервера - res.ok

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-31 20:47 UTC, andryxxa93 commented on src/components/App/App.tsx
> +    const getProductData = async () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-05-31 20:47 UTC, andryxxa93 commented on src/components/App/App.tsx
> +        const productList = await res.json();
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-05-31 20:47 UTC, andryxxa93 commented on src/components/BurgerIngredients/ProductList/ProductList.tsx
>    const dataMain = dataList.filter((item) => item.type === 'main');
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-05-31 20:47 UTC, andryxxa93 commented on src/components/Modal/Modal.tsx
> +      document.removeEventListener('keydown', onClickEsc);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-05-31 20:47 UTC, andryxxa93 commented on src/components/BurgerIngredients/ProductItem/ProductItem.tsx
> +const ProductItem = ({ dataItem, onClick }: IDataItemProps) => {
**Можно лучше**

используйте для компонентов обертку React.memo, которая позволяет сократить количество лишних рендеров и улучшить производительность

Например:

```
const SomeComponent = () => {
  return (
     ...........
  );
};

export default React.memo(SomeComponent);
```

https://ru.reactjs.org/docs/react-api.html#reactmemo
https://habr.com/ru/company/plarium/blog/442116/

2023-06-01 06:07 UTC, Jik789 commented on src/components/BurgerIngredients/ProductItem/ProductItem.tsx
> +const ProductItem = ({ dataItem, onClick }: IDataItemProps) => {
Использовал непосредственно для этого, но не совсем понял когда его лучше использовать а когда нет...

2023-06-01 06:15 UTC, Jik789 commented on src/components/BurgerIngredients/ProductList/ProductList.tsx
>    const dataMain = dataList.filter((item) => item.type === 'main');
> 

не совсем понял о чем Вы, можно на конкретном примере?

2023-06-01 15:52 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-06-01 15:54 UTC, merged